version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://geldzakje_user:geldzakje_password@db:5432/geldzakje_db
      - POSTGRES_PASSWORD=geldzakje_password
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: geldzakje_db
      POSTGRES_USER: geldzakje_user
      POSTGRES_PASSWORD: geldzakje_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U geldzakje_user -d geldzakje_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
